export const uiText = {
  zh: {
    progress: '司法进展',
    sources: '资料来源',
    details: '详细信息',
    empty: '图片加载失败,点击打开原图',
    openMenu: '打开菜单',
    closeMenu: '收起菜单',
    searchPlaceholder: '搜索',
    clearSearch: '清除搜索',
    searchEyebrow: '搜索',
    searchKeyword: '关键词',
    searchCountPrefix: '共',
    searchCountSuffix: '条',
    searchNoResults: '没有找到相关目录',
    searchEmptyContent: '没有找到相关内容',
    searchResultTitle: '搜索结果',
    returnPrevious: '返回上一页面',
    pressConferenceButton: '金秀贤记者会',
    siteViewsPrefix: '本站总访问量',
    siteViewsSuffix: '次',
  },
  ko: {
    progress: '법적 진행',
    sources: '자료 출처',
    details: '상세 정보',
    empty: '이미지를 불러오지 못했습니다. 원본을 열어 보세요',
    openMenu: '메뉴 열기',
    closeMenu: '메뉴 닫기',
    searchPlaceholder: '검색',
    clearSearch: '검색어 지우기',
    searchEyebrow: '검색',
    searchKeyword: '검색어',
    searchCountPrefix: '총',
    searchCountSuffix: '건',
    searchNoResults: '관련 목차가 없습니다',
    searchEmptyContent: '관련 내용을 찾지 못했습니다',
    searchResultTitle: '검색 결과',
    returnPrevious: '이전 화면으로',
    pressConferenceButton: '김수현 기자회견',
    siteViewsPrefix: '전체 방문 수',
    siteViewsSuffix: '회',
  },
  en: {
    progress: 'Legal progress',
    sources: 'Sources',
    details: 'Details',
    empty: 'Image failed to load. Click to open the original.',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    searchPlaceholder: 'Search',
    clearSearch: 'Clear search',
    searchEyebrow: 'Search',
    searchKeyword: 'Keyword',
    searchCountPrefix: 'Total',
    searchCountSuffix: 'results',
    searchNoResults: 'No matching sections',
    searchEmptyContent: 'No matching content',
    searchResultTitle: 'Search Results',
    returnPrevious: 'Back to previous view',
    pressConferenceButton: 'KSH Press Conference',
    siteViewsPrefix: 'Total site visits',
    siteViewsSuffix: '',
  },
}

export const languageNames = {
  zh: '中文',
  ko: '한국어',
  en: 'English',
}

export const timelineText = {
  zh: {
    year: '年份筛选',
    all: '全部年份',
    order: '时间顺序',
    desc: '最新优先',
    asc: '最早优先',
  },
  ko: {
    year: '연도 선택',
    all: '전체 연도',
    order: '시간 순서',
    desc: '최신순',
    asc: '오래된순',
  },
  en: {
    year: 'Filter by year',
    all: 'All years',
    order: 'Date order',
    desc: 'Newest First',
    asc: 'Oldest First',
  },
}
